name = "pwc-office-api"
main = "worker.js"
compatibility_date = "2024-09-04"

[vars]
ENVIRONMENT = "staging"

[[r2_buckets]]
binding = "PRIVATE_DATA"
bucket_name = "pwc-private-data"

[env.production]
name = "pwc-office-api-prod"

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.r2_buckets]]
binding = "PRIVATE_DATA"
bucket_name = "pwc-private-data"


